### ISSUE TITLE
Unable to run any pytorch model - Tensor type error

### ISSUE THREAD

**Issue by vikshiv** [CMU-SAFARI/TargetCall#1]
Hello,

I have been trying to correctly install TargetCall, but I am unable to run any model regardless of how I install. I even went as far as matching the conda version (4.7.12) on a Linux machine with a GPU. I still get the same error on other machines/other conda versions:

```python targetcall.py ../sample_data/fast5/ ../sample_data/Monkeypox_virus.fasta TINYX011 ../sample_data/

bonito basecaller ../bonito/models/TINYX011/ ../sample_data/fast5// --batchsize 3200 --modeltype tinynoskipx011 > ../sample_data//output.fastq
> loading model ../bonito/models/TINYX011/
> outputting unaligned fastq
> calling: 0 reads [00:00, ? reads/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/vshiv/software/TargetCall/bonito/multiprocessing.py", line 183, in run
    for k, v in self.iterator:
  File "/home/vshiv/software/TargetCall/bonito/ctc/basecall.py", line 24, in <genexpr>
    scores = (
  File "/home/vshiv/software/TargetCall/bonito/util.py", line 222, in <genexpr>
    return (
  File "/home/vshiv/software/TargetCall/bonito/util.py", line 217, in <genexpr>
    batches = (
  File "/home/vshiv/software/TargetCall/bonito/ctc/basecall.py", line 22, in <genexpr>
    (k, compute_scores(model, v)) for k, v in batchify(chunks, batchsize)
  File "/home/vshiv/software/TargetCall/bonito/ctc/basecall.py", line 39, in compute_scores
    probs = permute(model(chunks), 'TNC', 'NTC')
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vshiv/software/TargetCall/bonito/ctc/modeltinynoskipx011.py", line 33, in forward
    encoded = self.encoder(x)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vshiv/software/TargetCall/bonito/ctc/modeltinynoskipx011.py", line 205, in forward
    return self.encoder(x)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vshiv/software/TargetCall/bonito/ctc/modeltinynoskipx011.py", line 385, in forward
    _x = layer(_x)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vshiv/software/TargetCall/bonito/ctc/modeltinynoskipx011.py", line 241, in forward
    x = self.conv(x)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/vshiv/miniconda3/envs/targetcall/envs/target/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 297, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

```
I get the same error for any model I try. For reference, I am able to run Guppy and default Bonito models on this machine with this GPU. It seems like an issue with the Tensor type for one of the layers. Please let me know if there is any other info you need to resolve this issue!

I am using pytorch 1.10.2 (installed using the provided requirements.txt environment file)

**Comment by vshiv18** [comment]
Additionally, when the RuntimeError occurs, likely due to threading, the command hangs and the only way to cancel is ctrl-z and manually killing the process.

**Comment by vikshiv** [comment]
I added in a line for each model to autocast inputs, which seems to resolve the tensor type error. See PR #2.

**Comment by banucavlak** [comment]
Hello,

We are sorry for our late reply. We cannot reproduce the issue unfortunately in our setup. We thank you for your pull request and your contribution. Based on your changes, we have added autocast to top basecall code to fix the issue in a cleaner way. Since we cannot reproduce the issue, we are not sure if that solution solves your issue. Please let us know if the problem still continues for you.

Thanks!

**Comment by vikshiv** [comment]
Hello,

Thank you for looking into this! The latest commit with the higher-level autocast fix works for me now. I assume there is some system specific type issue in pytorch that was causing an issue, which casting fixes. I appreciate your following up on this and implementing the bug fix!

Best,
Vikram

**Comment by banucavlak** [comment]
Thanks for your response.

Best,
Banu
